export type Country = {
  name: string;
  code: string;
  phone: number;
  mask: string;
};

export const countries: Country[] = [
  { name: 'Afghanistan', code: 'AF', phone: 93, mask: 'XXX XXX XXXX' },
  { name: 'Aland Islands', code: 'AX', phone: 358, mask: 'XXX XXX XXXX' },
  { name: 'Albania', code: 'AL', phone: 355, mask: 'XXX XXX XXXX' },
  { name: 'Algeria', code: 'DZ', phone: 213, mask: 'XXX XXX XXXX' },
  { name: 'American Samoa', code: 'AS', phone: 1684, mask: '(XXX) XXX-XXXX' },
  { name: 'Andorra', code: 'AD', phone: 376, mask: '3XX XXX' },
  { name: 'Angola', code: 'AO', phone: 244, mask: 'XXX XXX XXX' },
  { name: 'Anguilla', code: 'AI', phone: 1264, mask: '(XXX) XXX-XXXX' },
  { name: 'Antarctica', code: 'AQ', phone: 672, mask: 'X XXX XXXX' },
  { name: 'Antigua and Barbuda', code: 'AG', phone: 1268, mask: '(XXX) XXX-XXXX' },
  { name: 'Argentina', code: 'AR', phone: 54, mask: '15 XXXX-XXXX' },
  { name: 'Armenia', code: 'AM', phone: 374, mask: 'XXX XXX XXX' },
  { name: 'Aruba', code: 'AW', phone: 297, mask: 'XXX XXXX' },
  { name: 'Australia', code: 'AU', phone: 61, mask: 'XXXX XXX XXX' },
  { name: 'Austria', code: 'AT', phone: 43, mask: 'XXXX XXX XXXX' },
  { name: 'Azerbaijan', code: 'AZ', phone: 994, mask: 'XXX XXX XX XX' },
  { name: 'Bahamas', code: 'BS', phone: 1242, mask: '(XXX) XXX-XXXX' },
  { name: 'Bahrain', code: 'BH', phone: 973, mask: 'XXXXXXXX' },
  { name: 'Bangladesh', code: 'BD', phone: 880, mask: 'XXXXX-XXXXXX' },
  { name: 'Barbados', code: 'BB', phone: 1246, mask: '(XXX) XXX-XXXX' },
  { name: 'Belarus', code: 'BY', phone: 375, mask: 'XX XXX XXXX' },
  { name: 'Belgium', code: 'BE', phone: 32, mask: 'XXXX XX XX XX' },
  { name: 'Belize', code: 'BZ', phone: 501, mask: 'XXX-XXXX' },
  { name: 'Benin', code: 'BJ', phone: 229, mask: 'XX XX XX XX' },
  { name: 'Bermuda', code: 'BM', phone: 1441, mask: '(XXX) XXX-XXXX' },
  { name: 'Bhutan', code: 'BT', phone: 975, mask: 'XXX XXX XXX' },
  { name: 'Bolivia', code: 'BO', phone: 591, mask: 'XXX-XXXX' },
  { name: 'Bonaire', code: 'BQ', phone: 599, mask: 'X XXX XXXX' },
  { name: 'Bosnia and Herzegovina', code: 'BA', phone: 387, mask: 'XXX XXX XXX' },
  { name: 'Botswana', code: 'BW', phone: 267, mask: 'XX XXX XXX' },
  { name: 'Bouvet Island', code: 'BV', phone: 55, mask: '(XX) XXXX-XXXX' },
  { name: 'Brazil', code: 'BR', phone: 55, mask: '(XX) XXXXX-XXXX' },
  { name: 'British Indian Ocean Territory', code: 'IO', phone: 246, mask: 'XXX XXXX' },
  { name: 'Brunei Darussalam', code: 'BN', phone: 673, mask: 'XXXX XXXX' },
  { name: 'Bulgaria', code: 'BG', phone: 359, mask: 'XXX XXX XXXX' },
  { name: 'Burkina Faso', code: 'BF', phone: 226, mask: 'XX XX XX XX' },
  { name: 'Burundi', code: 'BI', phone: 257, mask: 'XX XX XX XX' },
  { name: 'Cambodia', code: 'KH', phone: 855, mask: 'XX XXX XXX' },
  { name: 'Cameroon', code: 'CM', phone: 237, mask: 'XXX XX XX XX' },
  { name: 'Canada', code: 'CA', phone: 1, mask: '(XXX) XXX-XXXX' },
  { name: 'Cape Verde', code: 'CV', phone: 238, mask: 'XXX XX XX' },
  { name: 'Cayman Islands', code: 'KY', phone: 1345, mask: '(XXX) XXX-XXXX' },
  { name: 'Central African Republic', code: 'CF', phone: 236, mask: 'XX XX XX XX' },
  { name: 'Chad', code: 'TD', phone: 235, mask: 'XX XX XX XX' },
  { name: 'Chile', code: 'CL', phone: 56, mask: 'X XXXX XXXX' },
  { name: 'China', code: 'CN', phone: 86, mask: 'XXX XXXX XXXX' },
  { name: 'Christmas Island', code: 'CX', phone: 61, mask: 'XXXX XXX XXX' },
  { name: 'Cocos (Keeling) Islands', code: 'CC', phone: 672, mask: 'XXXX XXX XXX' },
  { name: 'Colombia', code: 'CO', phone: 57, mask: 'XXX XXX XXXX' },
  { name: 'Comoros', code: 'KM', phone: 269, mask: 'XXX XX XX' },
  { name: 'Congo', code: 'CG', phone: 242, mask: 'XX XXX XXXX' },
  { name: 'Congo (DRC)', code: 'CD', phone: 242, mask: 'XXXX XXX XXX' },
  { name: 'Cook Islands', code: 'CK', phone: 682, mask: 'XX XXX' },
  { name: 'Costa Rica', code: 'CR', phone: 506, mask: 'XXXX XXXX' },
  { name: "Cote D'Ivoire", code: 'CI', phone: 225, mask: 'XX XXX XXXX' },
  { name: 'Croatia', code: 'HR', phone: 385, mask: 'XXX XXX XXXX' },
  { name: 'Cuba', code: 'CU', phone: 53, mask: 'XXX XXXX' },
  { name: 'Curacao', code: 'CW', phone: 599, mask: 'X XXX XXXX' },
  { name: 'Cyprus', code: 'CY', phone: 357, mask: 'XXX XXXX' },
  { name: 'Czech Republic', code: 'CZ', phone: 420, mask: 'XXX XXX XXX' },
  { name: 'Denmark', code: 'DK', phone: 45, mask: 'XX XX XX XX' },
  { name: 'Djibouti', code: 'DJ', phone: 253, mask: 'XX XX XX XX' },
  { name: 'Dominica', code: 'DM', phone: 1767, mask: '(XXX) XXX-XXXX' },
  { name: 'Dominican Republic', code: 'DO', phone: 1809, mask: '(XXX) XXX-XXXX' },
  { name: 'Ecuador', code: 'EC', phone: 593, mask: 'XX XXX XXXX' },
  { name: 'Egypt', code: 'EG', phone: 20, mask: 'XXX XXXX XXXX' },
  { name: 'El Salvador', code: 'SV', phone: 503, mask: 'XXXX XXXX' },
  { name: 'Equatorial Guinea', code: 'GQ', phone: 240, mask: 'XXX XXX XXX' },
  { name: 'Eritrea', code: 'ER', phone: 291, mask: 'X XXX XXXX' },
  { name: 'Estonia', code: 'EE', phone: 372, mask: 'X XXXX XXXX' },
  { name: 'Ethiopia', code: 'ET', phone: 251, mask: 'X XX XXX XXX' },
  { name: 'Falkland Islands (Malvinas)', code: 'FK', phone: 500, mask: 'XXXXX' },
  { name: 'Faroe Islands', code: 'FO', phone: 298, mask: 'XXX XXX' },
  { name: 'Fiji', code: 'FJ', phone: 679, mask: 'XX XXX XXX' },
  { name: 'Finland', code: 'FI', phone: 358, mask: 'XXX XXX XXXX' },
  { name: 'France', code: 'FR', phone: 33, mask: 'XX XX XX XX XX' },
  { name: 'French Guiana', code: 'GF', phone: 594, mask: 'XXXX XX XX XX' },
  { name: 'French Polynesia', code: 'PF', phone: 689, mask: 'XX XX XX XX' },
  {
    name: 'French Southern Territories',
    code: 'TF',
    phone: 262,
    mask: 'XXXX XX XX XX',
  },
  { name: 'Gabon', code: 'GA', phone: 241, mask: 'XX XX XX XX' },
  { name: 'Gambia', code: 'GM', phone: 220, mask: 'XXX XXXX' },
  { name: 'Georgia', code: 'GE', phone: 995, mask: 'XXX XXX XXX' },
  { name: 'Germany', code: 'DE', phone: 49, mask: 'XXXX XXXX XXXX' },
  { name: 'Ghana', code: 'GH', phone: 233, mask: 'XXX XXX XXXX' },
  { name: 'Gibraltar', code: 'GI', phone: 350, mask: 'XXX XXXX' },
  { name: 'Greece', code: 'GR', phone: 30, mask: 'XXX XXX XXXX' },
  { name: 'Greenland', code: 'GL', phone: 299, mask: 'XX XX XX' },
  { name: 'Grenada', code: 'GD', phone: 1473, mask: '(XXX) XXX-XXXX' },
  { name: 'Guadeloupe', code: 'GP', phone: 590, mask: 'XXXX XX XX XX' },
  { name: 'Guam', code: 'GU', phone: 1671, mask: '(XXX) XXX-XXXX' },
  { name: 'Guatemala', code: 'GT', phone: 502, mask: 'XXXX XXXX' },
  { name: 'Guernsey', code: 'GG', phone: 44, mask: 'XXXXX XXXXXX' },
  { name: 'Guinea', code: 'GN', phone: 224, mask: 'XXX XX XX XX' },
  { name: 'Guinea-Bissau', code: 'GW', phone: 245, mask: 'X XXXXXX' },
  { name: 'Guyana', code: 'GY', phone: 592, mask: 'XXX XXXX' },
  { name: 'Haiti', code: 'HT', phone: 509, mask: 'XX XX XX XX' },
  {
    name: 'Heard Island and McDonald Islands',
    code: 'HM',
    phone: 672,
    mask: 'XXXX XXX XXX',
  },
  { name: 'Holy See (Vatican City State)', code: 'VA', phone: 379, mask: 'XXX XXXXX' },
  { name: 'Honduras', code: 'HN', phone: 504, mask: 'XXXX-XXXX' },
  { name: 'Hong Kong', code: 'HK', phone: 852, mask: 'XXXXXXXX' },
  { name: 'Hungary', code: 'HU', phone: 36, mask: 'XXX XXX XXXX' },
  { name: 'Iceland', code: 'IS', phone: 354, mask: 'XXX XXXX' },
  { name: 'India', code: 'IN', phone: 91, mask: 'XXX-XXX-XXXX' },
  { name: 'Indonesia', code: 'ID', phone: 62, mask: 'XXXX-XXXX-XXXX' },
  { name: 'Iran', code: 'IR', phone: 98, mask: 'XXXX XXX XXXX' },
  { name: 'Iraq', code: 'IQ', phone: 964, mask: 'XXX XXX XXXX' },
  { name: 'Ireland', code: 'IE', phone: 353, mask: 'XXX XXX XXXX' },
  { name: 'Isle of Man', code: 'IM', phone: 44, mask: 'XXXXX XXXXXX' },
  { name: 'Israel', code: 'IL', phone: 972, mask: 'XXX-XXX-XXXX' },
  { name: 'Italy', code: 'IT', phone: 39, mask: 'XXX XXX XXXX' },
  { name: 'Jamaica', code: 'JM', phone: 1876, mask: '(XXX) XXX-XXXX' },
  { name: 'Japan', code: 'JP', phone: 81, mask: 'XXX-XXXX-XXXX' },
  { name: 'Jersey', code: 'JE', phone: 44, mask: 'XXXXX XXXXXX' },
  { name: 'Jordan', code: 'JO', phone: 962, mask: 'XXX XXXX XXXX' },
  { name: 'Kazakhstan', code: 'KZ', phone: 7, mask: 'XXX XXX XXXX' },
  { name: 'Kenya', code: 'KE', phone: 254, mask: 'XXXX XXX XXX' },
  { name: 'Kiribati', code: 'KI', phone: 686, mask: 'XX XXX' },
  {
    name: "Korea (Democratic People's Republic of)",
    code: 'KP',
    phone: 850,
    mask: 'XXX XXX XXXX',
  },
  { name: 'Korea (Republic of)', code: 'KR', phone: 82, mask: 'XXX-XXXX-XXXX' },
  { name: 'Kuwait', code: 'KW', phone: 965, mask: 'XXXXXXXX' },
  { name: 'Kyrgyzstan', code: 'KG', phone: 996, mask: 'XXX XXX XXX' },
  { name: 'Lao PDR', code: 'LA', phone: 856, mask: 'XXX XXX XXXX' },
  { name: 'Latvia', code: 'LV', phone: 371, mask: 'XXXXXXXX' },
  { name: 'Lebanon', code: 'LB', phone: 961, mask: 'XX XXX XXX' },
  { name: 'Lesotho', code: 'LS', phone: 266, mask: 'XX XX XXXX' },
  { name: 'Liberia', code: 'LR', phone: 231, mask: 'XXX XXX XXX' },
  { name: 'Libya', code: 'LY', phone: 218, mask: 'XXX-XXXXXXX' },
  { name: 'Liechtenstein', code: 'LI', phone: 423, mask: 'XXX XXX XXXX' },
  { name: 'Lithuania', code: 'LT', phone: 370, mask: 'XX XXX XXXX' },
  { name: 'Luxembourg', code: 'LU', phone: 352, mask: 'XXX XXX XXX' },
  { name: 'Macao', code: 'MO', phone: 853, mask: 'XXXX XXXX' },
  { name: 'Macedonia, Republic of', code: 'MK', phone: 389, mask: 'XXX XXX XX' },
  { name: 'Madagascar', code: 'MG', phone: 261, mask: 'XX XX XXX XX' },
  { name: 'Malawi', code: 'MW', phone: 265, mask: 'XX XXX XXX' },
  { name: 'Malaysia', code: 'MY', phone: 60, mask: 'XXX-XXX XXXX' },
  { name: 'Maldives', code: 'MV', phone: 960, mask: 'XXXX XXXX' },
  { name: 'Mali', code: 'ML', phone: 223, mask: 'XX XX XX XX' },
  { name: 'Malta', code: 'MT', phone: 356, mask: 'XXX XXXXXX' },
  { name: 'Marshall Islands', code: 'MH', phone: 692, mask: 'XXXXX' },
  { name: 'Martinique', code: 'MQ', phone: 596, mask: 'XXXX XX XX XX' },
  { name: 'Mauritania', code: 'MR', phone: 222, mask: 'XXXX XXXXX' },
  { name: 'Mauritius', code: 'MU', phone: 230, mask: 'XXXX XXXX' },
  { name: 'Mayotte', code: 'YT', phone: 262, mask: 'XXXX XX XX XX' },
  { name: 'Mexico', code: 'MX', phone: 52, mask: 'XXX XXX XXXX' },
  { name: 'Micronesia, Federated States of', code: 'FM', phone: 691, mask: 'XXX XXX' },
  { name: 'Moldova', code: 'MD', phone: 373, mask: 'XXXX XXXX' },

  { name: 'Monaco', code: 'MC', phone: 377, mask: 'XX XX XX XX' },
  { name: 'Mongolia', code: 'MN', phone: 976, mask: 'XX XX XXXX' },
  { name: 'Montenegro', code: 'ME', phone: 382, mask: 'XXX XXXX' },
  { name: 'Montserrat', code: 'MS', phone: 1664, mask: '(XXX) XXX-XXXX' },
  { name: 'Morocco', code: 'MA', phone: 212, mask: 'XX XX XX XX XX' },
  { name: 'Mozambique', code: 'MZ', phone: 258, mask: 'XX XX XXX XXX' },
  { name: 'Myanmar', code: 'MM', phone: 95, mask: 'XXX XXX XXX XXX' },
  { name: 'Namibia', code: 'NA', phone: 264, mask: 'XX XXX XXXX' },
  { name: 'Nauru', code: 'NR', phone: 674, mask: 'XXX XXX' },
  { name: 'Nepal', code: 'NP', phone: 977, mask: 'XXX-XXX-XXXX' },
  { name: 'Netherlands', code: 'NL', phone: 31, mask: 'XX XXX XXXX' },
  { name: 'New Caledonia', code: 'NC', phone: 687, mask: 'XX XX XX' },
  { name: 'New Zealand', code: 'NZ', phone: 64, mask: 'XXX XXXX XXXX' },
  { name: 'Nicaragua', code: 'NI', phone: 505, mask: 'XXXX XXXX' },
  { name: 'Niger', code: 'NE', phone: 227, mask: 'XX XX XXXX' },
  { name: 'Nigeria', code: 'NG', phone: 234, mask: 'XXXX XXX XXXX' },
  { name: 'Niue', code: 'NU', phone: 683, mask: 'XXX XXX' },
  { name: 'Norfolk Island', code: 'NF', phone: 672, mask: 'XXX XXX' },
  { name: 'Northern Mariana Islands', code: 'MP', phone: 1670, mask: '(XXX) XXX-XXXX' },
  { name: 'Norway', code: 'NO', phone: 47, mask: 'XXX XX XXX' },
  { name: 'Oman', code: 'OM', phone: 968, mask: 'XXX XXX XX' },
  { name: 'Pakistan', code: 'PK', phone: 92, mask: 'XXXX-XXXXXXX' },
  { name: 'Palau', code: 'PW', phone: 680, mask: 'XXX XXXX' },
  { name: 'Palestine, State of', code: 'PS', phone: 970, mask: 'XXXX XXX XXX' },
  { name: 'Panama', code: 'PA', phone: 507, mask: 'XXXX XXXX' },
  { name: 'Papua New Guinea', code: 'PG', phone: 675, mask: 'XXX XX XX' },
  { name: 'Paraguay', code: 'PY', phone: 595, mask: 'XXX XXX XXX' },
  { name: 'Peru', code: 'PE', phone: 51, mask: 'XXX XXX XXX' },
  { name: 'Philippines', code: 'PH', phone: 63, mask: 'XXX XXX XXXX' },
  { name: 'Pitcairn', code: 'PN', phone: 64, mask: 'X XXX XXX' },
  { name: 'Poland', code: 'PL', phone: 48, mask: 'XXX XXX XXX' },
  { name: 'Portugal', code: 'PT', phone: 351, mask: 'XX XXX XXXX' },
  { name: 'Puerto Rico', code: 'PR', phone: 1787, mask: '(XXX) XXX-XXXX' },
  { name: 'Qatar', code: 'QA', phone: 974, mask: 'XX XXX XXXX' },
  { name: 'Réunion', code: 'RE', phone: 262, mask: 'XXXX XX XX XX' },
  { name: 'Romania', code: 'RO', phone: 40, mask: 'XX XX XXXX' },
  { name: 'Russian Federation', code: 'RU', phone: 7, mask: 'XXX XXX XX XX' },
  { name: 'Rwanda', code: 'RW', phone: 250, mask: 'XXX XXX XXXX' },
  { name: 'Saint Barthélemy', code: 'BL', phone: 590, mask: 'XXXX XX XX XX' },
  { name: 'Saint Helena', code: 'SH', phone: 290, mask: 'XXX' },
  { name: 'Saint Kitts and Nevis', code: 'KN', phone: 1869, mask: '(XXX) XXX-XXXX' },
  { name: 'Saint Lucia', code: 'LC', phone: 1758, mask: '(XXX) XXX-XXXX' },
  { name: 'Saint Martin (French part)', code: 'MF', phone: 590, mask: 'XXXX XX XX XX' },
  { name: 'Saint Pierre and Miquelon', code: 'PM', phone: 508, mask: 'XXX XX XX' },
  {
    name: 'Saint Vincent and the Grenadines',
    code: 'VC',
    phone: 1784,
    mask: '(XXX) XXX-XXXX',
  },
  { name: 'Samoa', code: 'WS', phone: 685, mask: 'XX XXX' },
  { name: 'San Marino', code: 'SM', phone: 378, mask: 'XXXX XXXX' },
  { name: 'Sao Tome and Principe', code: 'ST', phone: 239, mask: 'XX XX XXXX' },
  { name: 'Saudi Arabia', code: 'SA', phone: 966, mask: 'XXX XXXX XXX' },
  { name: 'Senegal', code: 'SN', phone: 221, mask: 'XX XXX XX XX' },
  { name: 'Serbia', code: 'RS', phone: 381, mask: 'XX XXXX XXXX' },
  { name: 'Seychelles', code: 'SC', phone: 248, mask: 'XX XX XX' },
  { name: 'Sierra Leone', code: 'SL', phone: 232, mask: 'XX XXX XXX' },
  { name: 'Singapore', code: 'SG', phone: 65, mask: 'XXXX XXXX' },
  { name: 'Sint Maarten (Dutch part)', code: 'SX', phone: 1721, mask: 'XXX XXXX' },
  { name: 'Slovakia', code: 'SK', phone: 421, mask: 'XX XX XXX XX' },
  { name: 'Slovenia', code: 'SI', phone: 386, mask: 'XX XXX XXX' },
  { name: 'Solomon Islands', code: 'SB', phone: 677, mask: 'XXXXX' },
  { name: 'Somalia', code: 'SO', phone: 252, mask: 'XX XXX XXX' },
  { name: 'South Africa', code: 'ZA', phone: 27, mask: 'XXX XXX XXXX' },
  {
    name: 'South Georgia and the South Sandwich Islands',
    code: 'GS',
    phone: 500,
    mask: 'XXXXX',
  },
  { name: 'South Sudan', code: 'SS', phone: 211, mask: 'XXX XXX XXXX' },
  { name: 'Spain', code: 'ES', phone: 34, mask: 'XXX XXX XXX' },
  { name: 'Sri Lanka', code: 'LK', phone: 94, mask: 'XXX XXX XXXX' },
  { name: 'Sudan', code: 'SD', phone: 249, mask: 'XX XXX XXXX' },
  { name: 'Suriname', code: 'SR', phone: 597, mask: 'XXX-XXXX' },
  { name: 'Svalbard and Jan Mayen', code: 'SJ', phone: 47, mask: 'XXX XX XXX' },
  { name: 'Sweden', code: 'SE', phone: 46, mask: 'XXX-XXX XX XX' },
  { name: 'Switzerland', code: 'CH', phone: 41, mask: 'XX XXX XXXX' },
  { name: 'Syrian Arab Republic', code: 'SY', phone: 963, mask: 'XXXX XXX XXX' },
  { name: 'Taiwan, Province of China', code: 'TW', phone: 886, mask: 'XXXX XXX XXX' },
  { name: 'Tajikistan', code: 'TJ', phone: 992, mask: 'XX XXX XXXX' },
  {
    name: 'Tanzania, United Republic of',
    code: 'TZ',
    phone: 255,
    mask: 'XXX XXX XXXX',
  },
  { name: 'Thailand', code: 'TH', phone: 66, mask: 'XXX XXX XXXX' },
  { name: 'Timor-Leste', code: 'TL', phone: 670, mask: 'XXX XXX XXXX' },
  { name: 'Togo', code: 'TG', phone: 228, mask: 'XX XX XXXX' },
  { name: 'Tokelau', code: 'TK', phone: 690, mask: 'XXXX' },
  { name: 'Tonga', code: 'TO', phone: 676, mask: 'XXXX' },
  { name: 'Trinidad and Tobago', code: 'TT', phone: 1868, mask: '(XXX) XXX-XXXX' },
  { name: 'Tunisia', code: 'TN', phone: 216, mask: 'XX XXX XXX' },
  { name: 'Turkey', code: 'TR', phone: 90, mask: 'XXX XXX XXXX' },
  { name: 'Turkmenistan', code: 'TM', phone: 993, mask: 'XX XXX XXX' },
  { name: 'Tuvalu', code: 'TV', phone: 688, mask: 'XXXX' },
  { name: 'Uganda', code: 'UG', phone: 256, mask: 'XXX XXX XXXX' },
  { name: 'Ukraine', code: 'UA', phone: 380, mask: 'XXXX XXX XXXX' },
  { name: 'United Arab Emirates', code: 'AE', phone: 971, mask: 'XXX XXX XXXX' },
  {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    code: 'GB',
    phone: 44,
    mask: 'XXXXX XXXXXX',
  },
  { name: 'United States of America', code: 'US', phone: 1, mask: '(XXX) XXX-XXXX' },
  { name: 'Uruguay', code: 'UY', phone: 598, mask: 'XXX XXX XXX' },
  { name: 'Uzbekistan', code: 'UZ', phone: 998, mask: 'XX XXX XXXX' },
  { name: 'Vanuatu', code: 'VU', phone: 678, mask: 'XX XXX' },
  {
    name: 'Venezuela (Bolivarian Republic of)',
    code: 'VE',
    phone: 58,
    mask: 'XXXX-XXXXXXX',
  },
  { name: 'Viet Nam', code: 'VN', phone: 84, mask: 'XXX XXX XXXX' },
  { name: 'Western Sahara', code: 'EH', phone: 212, mask: 'XXXX-XXXXX' },
  { name: 'Yemen', code: 'YE', phone: 967, mask: 'XXX XXX XXX' },
  { name: 'Zambia', code: 'ZM', phone: 260, mask: 'XXX XXX XXX' },
  { name: 'Zimbabwe', code: 'ZW', phone: 263, mask: 'XXX XXX XXXX' },
];

export const defaultCountry = {
  name: 'Brazil',
  code: 'BR',
  phone: 55,
  mask: '(XX) XXXXX-XXXX',
};
